# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klvr', '0002_auto_20170107_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='auth.Tag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(related_name='task_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
